# This file is part of the research.fi API service
#
# Copyright 2019 Ministry of Education and Culture, Finland
#
# :author: CSC - IT Center for Science Ltd., Espoo Finland servicedesk@csc.fi
# :license: MIT

# Dockerfile for development. Overrides values from docker-compose.yml.
# Nginx is disabled, Django development server is used. Django debug mode is enabled.
version: '3.7'

services:
  django:
    build: ./django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django/webapps/:/usr/src/webapps/
    ports:
      - 8000:8000
    environment:
     - DEBUG=1
  nginx:
    command: echo "Nginx disabled"