# This file is part of the research.fi API service
#
# Copyright 2019 Ministry of Education and Culture, Finland
#
# :author: CSC - IT Center for Science Ltd., Espoo Finland servicedesk@csc.fi
# :license: MIT

# Dockerfile for production.
# Nginx is used as webserver. Django application is served by Gunicorn. Django debug mode is disabled.
version: '3.7'

services:
  django:
    build: ./django
    command: pipenv run gunicorn webapps.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    environment:
      - DEBUG=0
      - DJANGO_ENV_SECRET_KEY=${DJANGO_ENV_SECRET_KEY}
      - DJANGO_ENV_ELASTICSEARCH_HOST=${DJANGO_ENV_ELASTICSEARCH_HOST}
  nginx:
    build: ./nginx
    ports:
      - 8888:8888
    depends_on:
      - django